---
title: TexOps.io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
bio: A Texas Sized Journey Into DevOps
description: You're either the one that creates the automation or you're getting automated.
  - Tom Preston-Werner
reading_time: true
words_per_minute: 200
logo: "/uploads/logo.jpg"
background: assets/img/placeholder-big.jpg
tiled_bg: false
locale: en_US
url: https://taylantatli.github.io/Moon
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed
disqus_shortname: taylantatli
twitter: username
facebook: mattdreynolds
github-url: username
instagram: mdrtp
steam: username
gems:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
